name: Build Focus App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用最新的macOS运行环境
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
        
    - name: Build macOS app
      run: |
        # 检查环境
        echo "Xcode version:"
        xcodebuild -version
        
        # 列出scheme
        echo "Available schemes:"
        xcodebuild -list -project Focus.xcodeproj || echo "Error: Could not list schemes"
        
        # 创建构建目录
        mkdir -p ./Build
        
        # 尝试构建应用
        echo "Building Focus app..."
        xcodebuild build -project Focus.xcodeproj -configuration Release -derivedDataPath ./DerivedData CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
        
        # 查找并复制构建产物
        echo "Searching for built app:"
        find ./DerivedData -name "*.app" -type d
        
        APP_PATH=$(find ./DerivedData -name "*.app" -type d | head -1)
        if [ -n "$APP_PATH" ]; then
          echo "Found app at: $APP_PATH"
          cp -R "$APP_PATH" ./Build/Focus.app
          cd ./Build
          zip -r Focus.zip Focus.app
          echo "Archive created successfully:"
          ls -la Focus.zip
        else
          echo "Error: No app files found!"
          exit 1
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Focus-app
        path: Build/Focus.zip
        
    # 如果你想发布到GitHub Releases，取消以下注释
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: |
    #       Build/Focus.zip
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 