name: Build Focus App

permissions:
  actions: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version
      
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
        
    - name: Build macOS app
      run: |
        echo "Xcode version:"
        xcodebuild -version
        
        echo "Available schemes:"
        xcodebuild -list -project Focus.xcodeproj || echo "Error: Could not list schemes"
        
        mkdir -p ./Build
        
        echo "Building Focus app..."
        xcodebuild build -project Focus.xcodeproj -configuration Release -derivedDataPath ./DerivedData CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO
        
        echo "Searching for built app:"
        find ./DerivedData -name "*.app" -type d
        
        APP_PATH=$(find ./DerivedData -name "*.app" -type d | head -1)
        if [ -n "$APP_PATH" ]; then
          echo "Found app at: $APP_PATH"
          cp -R "$APP_PATH" ./Build/Focus.app
          cd ./Build
          zip -r Focus.zip Focus.app
          echo "Archive created successfully:"
          ls -la Focus.zip
        else
          echo "Error: No app files found!"
          exit 1
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4  # Updated to latest version
      with:
        name: Focus-app
        path: Build/Focus.zip